package com.example.controller;

import com.example.handler.AmazonHandler;
import com.example.handler.AmazonMessageSender;
import com.example.model.Order;
import com.example.model.Truck;
import com.example.model.User;
import com.example.proto.amazon_ups.AmazonUPSProto;
import com.example.service.OrderService;
import com.example.service.TruckService;
import com.example.service.UserService;
import com.example.utils.JwtUtil;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.mail.MailException;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionStatus;
import org.springframework.transaction.support.DefaultTransactionDefinition;
import org.springframework.web.bind.annotation.*;
import com.example.utils.PasswordUtil;
import org.springframework.web.servlet.view.RedirectView;

import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.web.bind.annotation.GetMapping;

//This controller maps the root path ("/") to the index.html file generated by the Vue.js build.
@Controller
public class VueController {

    private final JavaMailSender emailSender;
    private final UserService userService;
    private final TruckService truckService;
    private final OrderService orderService;
    private final PlatformTransactionManager transactionManager;
    private final ApplicationContext applicationContext;
    private AmazonHandler amazonHandler;

    @Autowired
    public VueController(UserService userService, TruckService truckService, OrderService orderService, JavaMailSender emailSender, PlatformTransactionManager transactionManager, ApplicationContext applicationContext, AmazonHandler amazonHandler) {
        this.userService = userService;
        this.truckService = truckService;
        this.orderService = orderService;
        this.emailSender = emailSender;
        this.transactionManager = transactionManager;
        this.applicationContext = applicationContext;
        this.amazonHandler = amazonHandler;
    }

    @GetMapping("/")
    public String index() {
        return "index";
    }

    @GetMapping("/mylogin")
    public String mylogin() {
        return "index";
    }


    @GetMapping("/changepwd")
    public RedirectView changepwd() {
        return new RedirectView("/");
    }

    @GetMapping("/tracking")
    public String tracking() {
        return "index";
    }

    @PostMapping("/tracking")
    public ResponseEntity<List<Order>> trackOrder(@RequestBody Map<String, String> request) {
        String shipId = request.get("shipId");
        System.out.println("Received shipId in tracking: " + shipId);
        Order myorder;
        List<Order> orders = new ArrayList<>(1);
        if (shipId != null && !shipId.isEmpty()) {
            myorder = orderService.getOrderByShipId(Long.valueOf(shipId));
            if (myorder != null) {
                orders.add(myorder);
            }
        }
        return ResponseEntity.ok(orders);
    }

    @PostMapping("/orderdetail")
    public ResponseEntity<Order> orderDetail
            (@RequestBody Map<String, String> request) {
        // edit_mode = 0; query the order
        // edit_mode = 1; update the order
        // edit_mode = 2; cancel the order
        // edit_mode = 3; query the truck destination
        String shipId = request.get("shipId");
        String mode = request.get("edit_mode");
        if (mode.equals("1")) {
            String newX = request.get("newX");
            String newY = request.get("newY");
            System.out.println("edit mode is 1");
            System.out.println("X: " + newX);
            System.out.println("Y: " + newY);
            DefaultTransactionDefinition definition = new DefaultTransactionDefinition();
            TransactionStatus status = transactionManager.getTransaction(definition);
            try {
                Order myorder = orderService.getOrderByShipId(Long.valueOf(shipId));
                String orderStatus = myorder.getShipmentStatus();
                boolean ifEdit = orderStatus.equals("CREATED") || orderStatus.equals("TRUCK EN ROUTE TO WAREHOUSE") || orderStatus.equals("TRUCK WAITING FOR PACKAGE");
                if (ifEdit) {
                    // order can be changed -> update database -> return new order info
                    myorder.setX(Integer.parseInt(newX));
                    myorder.setY(Integer.parseInt(newY));
                    orderService.updateOrder(myorder);
                    transactionManager.commit(status);
                    //send UAUpdatePackageAddress to Amazon
                    Long msgSeqNum = amazonHandler.getAndAddSeqNumToAmazon();
                    amazonHandler.getUnAckedNums().add(msgSeqNum);
                    AmazonMessageSender amazonMessageSender = applicationContext.getBean(AmazonMessageSender.class);
                    AmazonUPSProto.UAUpdatePackageAddress uaUpdatePackageAddress = AmazonUPSProto.UAUpdatePackageAddress.newBuilder()
                            .setShipid(Long.parseLong(shipId))
                            .setX(Integer.parseInt(newX))
                            .setY(Integer.parseInt(newY))
                            .setSeqnum(msgSeqNum)
                            .build();
                    amazonMessageSender.setUaUpdatePackageAddress(uaUpdatePackageAddress);
                    amazonMessageSender.setSeqNum(msgSeqNum);//!!!!
                    Thread amazonMsgSenderThread = new Thread(amazonMessageSender);
                    amazonMsgSenderThread.start();
                    return ResponseEntity.ok(myorder);
                } else {
                    transactionManager.commit(status);
                    // cannot be changed -> return old order info and error to change it
                    Order orderEdit = new Order(-99L, myorder.getUserId(), myorder.getShipmentStatus(), myorder.getId(), myorder.getDescription(), myorder.getX(), myorder.getY(), myorder.getWhId(), myorder.getCreatedTime());
                    orderEdit.setTruckId(myorder.getTruckId());
                    orderEdit.setDeliveringTime(myorder.getDeliveringTime());
                    orderEdit.setDeliveredTime(myorder.getDeliveredTime());
                    return ResponseEntity.ok(orderEdit);
                }
            } catch (Exception e) {
                // Roll back the transaction in case of an error
                transactionManager.rollback(status);
                throw e;
            }

        } else if (mode.equals("0")) {
            Order myorder = orderService.getOrderByShipId(Long.valueOf(shipId));
            return ResponseEntity.ok(myorder);
        } else if (mode.equals("2")) {
            boolean ifCancel = false;
            if (ifCancel) {
                // cancel order success -> get data info -> delete database -> redirect to home page
                Order myorder = orderService.getOrderByShipId(Long.valueOf(shipId));
                return ResponseEntity.ok(myorder);
            } else {
                // cancel order failure
                Order orderCancel = new Order(-99L, "DELIVERING", 1L, "description1", 11, 11, 1, LocalDateTime.now());
                return ResponseEntity.ok(orderCancel);
            }
        } else {
            String truckId = request.get("truckId");
            Order myorder = orderService.getOrderByShipId(Long.valueOf(shipId));
            Truck mytruck = truckService.getTruckById(1);
            myorder.setX(mytruck.getX());
            myorder.setY(mytruck.getY());
            return ResponseEntity.ok(myorder);
        }
    }

    @GetMapping("/myorder")
    public ResponseEntity<List<Order>> myorder
            (@RequestHeader(value = "Authorization", required = false) String authHeader) throws SQLException {
        if (authHeader == null) {
            return ResponseEntity.status(HttpStatus.FOUND).header(HttpHeaders.LOCATION, "/mylogin").build();
        }
        String authToken = authHeader.replace("Bearer ", "");
        String userId = JwtUtil.getUsernameFromToken(authToken);
        List<Order> orders = userService.getOrdersByUserId(userId);
        return ResponseEntity.ok(orders);
    }

    @GetMapping("/signup")
    public String signup() {
        return "index";
    }

    @PostMapping("/signup")
    public ResponseEntity<?> signUp(@RequestBody Map<String, String> req) {
        String userId = req.get("userId");
        String email = req.get("email");
        String password = req.get("password");
        try {
// String salt = PasswordUtil.generateSalt();
            String hashedPassword = PasswordUtil.hashPassword(password, "saltECE568love");
            User myuser = new User(userId, email, hashedPassword);
// myuser.setSalt(salt);
            userService.addUser(myuser);
// after signup, login directly and save account into JWT
            String token = JwtUtil.generateToken(userId);
            Map<String, Object> responseBody = new HashMap<>();
            responseBody.put("token", token);
            responseBody.put("userInfo", myuser);
            // send the email
            SimpleMailMessage message = new SimpleMailMessage();
            message.setFrom("temp_for_project@outlook.com");
            message.setTo(email);
            message.setSubject("SignUp for mini UPS.");
            String textBody = "Dear " + userId + ",\n\n"
                    + "Welcome to Mini UPS! We appreciate your decision to sign up with us.\n\n"
                    + "Best regards,\n\n" + "mini-ups-team";
            message.setText(textBody);
            emailSender.send(message);
            return ResponseEntity.ok(responseBody);
        } catch (SQLException e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Oops, something wrong. Try another userId.");
        }
    }

    @PostMapping("/mylogin")
    public ResponseEntity<?> login(@RequestBody Map<String, String> req) {
        String userId = req.get("userId");
        String password = req.get("password");
        System.out.println("Login user: " + userId);
        User myuser = userService.getUserById(userId);
        if (myuser != null) {
            String hashedPassword = PasswordUtil.hashPassword(password, "saltECE568love");
            if (myuser.getPassword().equals(hashedPassword)) {
                // login successfully, create and save JWT,session or Token
                //1. login successfully, create JWT
                String token = JwtUtil.generateToken(userId);
                //2. create JSON obj, including JWT
                Map<String, Object> responseBody = new HashMap<>();
                responseBody.put("token", token);
                responseBody.put("userInfo", myuser);
                //3. return JSON obj
                return ResponseEntity.ok(responseBody);
            } else {
                System.out.println("Password is not the same");
                return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Invalid password");
            }
        } else {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("User not found");
        }
    }

    @GetMapping("/profile")
    public ResponseEntity<?> profile(@RequestHeader(value = "Authorization") String authHeader) {
        String authToken = authHeader.replace("Bearer ", "");
        String userId = JwtUtil.getUsernameFromToken(authToken);
        System.out.println("Look at profile of: " + userId);
        User myuser = userService.getUserById(userId);
        if (myuser != null) {
            String email = myuser.getEmail();
            return ResponseEntity.ok(email);
        } else {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("User not found");
        }
    }

    @PostMapping("/profile")
    public ResponseEntity<?> editProfile(@RequestHeader(value = "Authorization") String authHeader,
                                         @RequestBody Map<String, String> req) throws SQLException {
        String newEmail = req.get("newEmail");
        String authToken = authHeader.replace("Bearer ", "");
        String userId = JwtUtil.getUsernameFromToken(authToken);
        User myuser = userService.getUserById(userId);
        if (myuser != null) {
            myuser.setEmail(newEmail);
            userService.updateUser(myuser);
            SimpleMailMessage message = new SimpleMailMessage();
            message.setFrom("temp_for_project@outlook.com");
            message.setTo(newEmail);
            message.setSubject("SignUp for mini UPS.");
            String textBody = "Dear " + userId + ",\n\n"
                    + "Welcome to Mini UPS! We realize you have changed your email address.\n\n"
                    + "Best regards,\n\n" + "mini-ups-team";
            message.setText(textBody);
            emailSender.send(message);
            return ResponseEntity.ok(myuser.getEmail());
        } else {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("User not found");
        }
    }

    @GetMapping("/logout")
    public RedirectView logout() {
        return new RedirectView("/", true);
    }

    @PostMapping("/logout")
    public ResponseEntity<String> logout(HttpServletRequest request) {
        System.out.println("Now doing logout");
        String headerAuth = request.getHeader("Authorization");

        // Check if headerAuth is not null before calling substring()
        if (headerAuth != null && headerAuth.startsWith("Bearer ")) {
            String jwtToken = headerAuth.substring(7);
            String userId = JwtUtil.getUsernameFromToken(jwtToken);
            System.out.println("User want to log out: " + userId);
            return ResponseEntity.ok(userId);
        } else {
            // Handle the case where the Authorization header is missing or invalid
            System.out.println("Authorization header is missing or invalid");
            // You might want to return a different response or throw an exception here
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Authorization header is missing or invalid");
        }
    }

    @PostMapping("/changepwd")
    public ResponseEntity<?> changepwd(@RequestBody Map<String, String> request, @RequestHeader("Authorization") String authHeader) {
        System.out.println("Now doing change pwd");
        String oldPassword = request.get("oldPassword");
        String oldHashedPassword = PasswordUtil.hashPassword(oldPassword, "saltECE568love");
        String newPassword = request.get("newPassword");
        String newHashedPassword = PasswordUtil.hashPassword(newPassword, "saltECE568love");

        String authToken = authHeader.replace("Bearer ", "");
        String userId = JwtUtil.getUsernameFromToken(authToken);
        User myuser = userService.getUserById(userId);

        if (myuser.getPassword().equals(oldHashedPassword)) {
            System.out.println("old pwd: correct");
            myuser.setPassword(newHashedPassword);
            try {
                userService.updateUser(myuser);
                System.out.println("new pwd: done");
                return ResponseEntity.ok("Password changed successfully.");
            } catch (SQLException e) {
                return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Oops, database wrong! sad...");
            }
        } else {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Old password is not correct");
        }
    }
}
