package com.example.controller;

import com.example.model.Truck;
import com.example.model.User;
import com.example.service.OrderService;
import com.example.service.TruckService;
import com.example.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

//test
//This controller maps the root path ("/") to the index.html file generated by the Vue.js build.
@Controller
public class VueController {

    private final UserService userService;
    private final TruckService truckService;
    private final OrderService orderService;

    @Autowired
    public VueController(UserService userService, TruckService truckService, OrderService orderService){
        this.userService=userService;
        this.truckService=truckService;
        this.orderService=orderService;
    }

    @GetMapping("/")
    public String index() {
        return "index";
    }
}
