version: '2'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot123
      MYSQL_DATABASE: project
    ports:
      - 23333:3306
  project:
    container_name: project
    build: ./ups
    image: project:latest
    command: bash -c "sleep 3 && java -jar /app/ups-0.0.1-SNAPSHOT.jar vcm-32315.vm.duke.edu"
    volumes:
      - ./ups/build/libs:/app
    ports:
      - 34567:34567
      - 8080:8080
    depends_on:
      - mysql
